// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as TextDirection } from './TextDirection';

/** Identifier type for public.language */
export type LanguageIsoCode = string & { __brand: 'LanguageIsoCode' };

/** Represents the table public.language */
export default interface Language {
  iso_code: LanguageIsoCode;

  name: string;

  direction: TextDirection;

  text_home: string;
}

/** Represents the initializer for the table public.language */
export interface LanguageInitializer {
  iso_code: LanguageIsoCode;

  name: string;

  direction: TextDirection;

  text_home: string;
}

/** Represents the mutator for the table public.language */
export interface LanguageMutator {
  iso_code?: LanguageIsoCode;

  name?: string;

  direction?: TextDirection;

  text_home?: string;
}
