// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.project */
export type ProjectId = string & { __brand: 'ProjectId' };

/** Represents the table public.project */
export default interface Project {
  id: ProjectId;

  image_path: string | null;

  github_url: string | null;

  website_url: string | null;
}

/** Represents the initializer for the table public.project */
export interface ProjectInitializer {
  /** Default value: gen_random_uuid() */
  id?: ProjectId;

  image_path?: string | null;

  github_url?: string | null;

  website_url?: string | null;
}

/** Represents the mutator for the table public.project */
export interface ProjectMutator {
  id?: ProjectId;

  image_path?: string | null;

  github_url?: string | null;

  website_url?: string | null;
}
