// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.text_direction */
enum TextDirection {
  rtl = 'rtl',
  ltr = 'ltr',
};

export default TextDirection;
